on:
  push:
    branches:
      - develop
      - "release/**"
      - master
name: Release - Deploy Guest App to AWS S3 and Create PR to Backend using Github Actions
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Run number with offset
      env:
        NUM: ${{ github.run_number }}
      run: |
       echo "GITHUB_RUN_NUMBER_WITH_OFFSET=$(($NUM+2000))" >> $GITHUB_ENV
    - run: echo ${{ env.GITHUB_RUN_NUMBER_WITH_OFFSET }}
    - name: Checkout
      uses: actions/checkout@master 
    - name: Create pull request
      env:
        INPUT_SOURCE_FOLDER: 'pull_request/guest-app.html'
        INPUT_DESTINATION_BASE_BRANCH: '${GITHUB_REF#refs/heads/}'
        INPUT_DESTINATION_HEAD_BRANCH: 'guest-build-v${{ env.GITHUB_RUN_NUMBER_WITH_OFFSET }}'
        BRANCH_NAME: ${{ github.head_ref }} 
        BRANCH_NAME1: ${{ github.ref_name }} 
      run: |
        echo "${BRANCH_NAME}"
        echo "${BRANCH_NAME1}"
        echo "something"
